### PR TITLE
Fixed issue #49

### PR DESCRIPTION
**Pull request by acalatrava**
added 'extra' parameter to the init

### CODE REVIEW

**Comment by hiennguyen92** [comment]
@acalatrava you can add more props by setting directly. 
```
 let data = flutter_callkit_incoming.Data(id: UUID().uuidString, nameCaller: nameCaller, handle: handle, type: isVideo ? 1 : 0)
        data.nameCaller = "Johnny"
....
```

**Comment by hiennguyen92** [comment]
Object-c
```
(), ^(void){
        Data * data = [[Data alloc]initWithId:@"44d915e1-5ff4-4bed-bf13-c423048ec97a" nameCaller:@"Hien Nguyen" handle:@"0123456789" type:1];
        [data setNameCaller:@"Johnny"];
        [data setExtra:@{ @"userId" : @"HelloXXXX", @"key2" : @"value2"}];
        [SwiftFlutterCallkitIncomingPlugin.sharedInstance showCallkitIncoming:data fromPushKit:YES];
....
```

**Comment by acalatrava** [comment]
Mmmm but that won’t fix the extra data pushed from the server, right?

**Comment by acalatrava** [comment]
You were right, my mistake 👍

**Pull request closed without merging**
