### PR TITLE
Draft: Allow to call showCallkitIncoming() from Objective C code

### PR DESCRIPTION
**Pull request by marcoberetta96**
hi @hiennguyen92 

I've added these few lines to allow the method `showCallkitIncoming` to be called from Objective C (https://github.com/hiennguyen92/flutter_callkit_incoming/issues/21)

Still a problem remains.
The initializer of `Data` takes a `[String: Any?]` as param, which cannot be represented in Objective-C.
Can you change it to something representable in Objective-C?

Thanks

### CODE REVIEW

**Comment by marcoberetta96** [comment]
Hi @hiennguyen92 , any update on this?
If you tell me how can I change `[String: Any?]` into something can be represented in Objective-C I can do the work and test all.

**Comment by hiennguyen92** [comment]
@marcoberetta96 sorry for late. I will update version using for Object-C soon.

**Comment by marcoberetta96** [comment]
@hiennguyen92 do you have any ETA time for this? Just to know :)

**Comment by hiennguyen92** [comment]
Hi @marcoberetta96

for Objective-C
```objc
#if __has_include(<flutter_callkit_incoming/flutter_callkit_incoming-Swift.h>)
  #import <flutter_callkit_incoming/flutter_callkit_incoming-Swift.h>
  #else
  #import "flutter_callkit_incoming-Swift.h"
  #endif


Data * data = [[Data alloc]initWithId:@"44d915e1-5ff4-4bed-bf13-c423048ec97a" nameCaller:@"Hien Nguyen" handle:@"0123456789" type:1];
[SwiftFlutterCallkitIncomingPlugin.sharedInstance showCallkitIncoming:data fromPushKit:YES];
```

**Comment by marcoberetta96** [comment]
closing since not needed anymore

**Pull request closed without merging**
