### PR TITLE
Implement dart class models instead using dynamic types and Maps

### PR DESCRIPTION
**Pull request by icodelifee**
This is a breaking change that introduces Dart Class models to this package.
Using dynamic types are prone to bug and its easier to use Dart class models instead of Maps

I have done my best to refactor the required changes for this feature. 
There aren't changes internally that would change the behavior of this package.

Please let me know if there are any changes required.
Thanks

### CODE REVIEW

**Comment by AAkira** [comment]
Thanks!! @icodelifee 
I've always wanted to make the same change.

**Comment by JulianBissekkou** [comment]
Great PR, can we get this merged @hiennguyen92 ?

**Comment by stefanschaller** [comment]
Would love to see this in the next version. @hiennguyen92

**Comment by booooohdan** [comment]
@hiennguyen92 please, do something or grant access to another contributor if you don't work on this package

**Comment by ozalisky** [comment]
> @hiennguyen92 please, do something or grant access to another contributor if you don't work on this package

You always can fork the package and work on it yourself. What's the point to spam here?

**Comment by hiennguyen92** [comment]
thanks you.

**Pull request merged**
