### PR TITLE
Added permission for full screen intents in android 14

### PR DESCRIPTION
**Pull request by Spyspyspy**
#544 it should close this issue. I've added a native function to move users to the settings for accepting this permissions. After it Lock Screen wakes successfully.

### CODE REVIEW

**Comment by kavinrs01** [comment]
How can I check if FlutterCallkitIncoming.requestFullIntentPermission() has already been granted, so it doesn't prompt the user for permission every time the app is launched?

**Comment by Abdullah-319** [comment]
even the FlutterCallkitIncoming.requestFullIntentPermission() returns true but the app doesnot show tha call ui on lock screen, the issue persists. @Spyspyspy

**Comment by Spyspyspy** [comment]
> even the FlutterCallkitIncoming.requestFullIntentPermission() returns true but the app doesnot show tha call ui on lock screen, the issue persists. @Spyspyspy

Hey, thank you for the response! I will check it and fix, when I have a free time.

**Comment by Abdullah-319** [comment]
@Spyspyspy Hello Dimitrii,
I am a Abdullah Ahmad, mobile application developer with 3+ years of experience. I am facing several issues in the implementation of the one-to-one audio call in my flutter application using the livekit. Can you please me in this regard. I would appreciate it very much. Here is my email abdullahahmad319.31@gmail.com
Thankyou

**Comment by Spyspyspy** [comment]
Hello, what problems do you have?

Чт, 2 окт. 2025 г. в 22:35, Abdullah Ahmad ***@***.***>:

**Pull request merged**
